wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: GCN
dataset:
  desc: null
  value: AAPL
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692784463.782596
    t:
      1:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      3:
      - 1
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 5
